spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5432/postgres
    username: postgres
    password: 111

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: validate


logging.level:
  ROOT: INFO
  com.epam: INFO
  org.springframework: INFO