spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://127.0.0.1:5433/ib
    username: postgres
    password: admin

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    properties:
      hibernate:
        jdbc.lob.non_contextual_creation: true
        format_sql: true
    show-sql: true
    hibernate:
      ddl-auto: update


logging:
  level:
    ROOT: INFO
    com.epam: INFO
    org.springframework: INFO
    org.springframework.security: INFO
    org.hibernate: WARN

  pattern:
    console:  "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} Session ID [%X{sessionID}] - %msg%n"
    file: "%d %p %c{1.} [%t] Session ID [%X{sessionID}] %m%n"
  file: webchat.log
